name: Build Lustre with ZFS

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  ZFS_REPO: https://github.com/zulinfan/zfs-ci.git
  ZFS_BRANCH: main

jobs:
  build:
    runs-on: self-hosted
    steps:
    - name: Checkout Lustre repository
      uses: actions/checkout@v3

    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo xargs --arg-file=.github/workflows/build-dependencies.txt apt-get install -qq

    - name: Clone and build ZFS
      run: |
        git clone --branch $ZFS_BRANCH $ZFS_REPO zfs --depth=1
        cd zfs
        ./autogen.sh
        ./configure --prefix=/usr
        make --no-print-directory --silent -j$(nproc)
        sudo make install
        if [ -z "$(grep extra /etc/depmod.d/ubuntu.conf)" ]; then
            sudo sed -i.bak 's/updates/extra updates/' /etc/depmod.d/ubuntu.conf
        fi

    - name: Build Lustre from checked out repository
      run: |
        ./autogen.sh
        ./configure --with-zfs=$(pwd)/zfs --disable-ldiskfs
        make -j$(nproc)
        sudo make install

    - name: Verify installation
      run: |
        sudo depmod -a
        sudo modprobe zfs
        sudo modprobe lustre
        sudo /sbin/lctl list_nids

    - name: Acceptance-small tests
      run: |
        cd /usr/lib/lustre/tests
        sudo env FSTYPE=zfs ./acceptance-small.sh

    - name: Cleanup installation
      run: |
        sudo lustre_rmmod
        sudo modprobe -r zfs
        sudo make uninstall
        cd zfs
        sudo make uninstall

